### PR TITLE
user: fix user's birthday can be future

### LINKED ISSUE #327: User can be born in the future

### PR DESCRIPTION
**Pull request by Nhqml**
Fix #327

Apply @lportemo's feedback from #329

### CODE REVIEW

**Review by lportemo — CHANGES_REQUESTED** [review]
After some thinking can't we implement this check on the property is_young_enough_to_compete on contestant models?  As a result, the "too young" candidate will not be shown in corrections interface.

And maybe we should emphasize on the importance of the DOB in the form template.

What do you think ?

**Comment by Elfikurr** [comment]
I believe that this should be done anywhere you want.
But adding a message saying the date of birth will be used for the rest of the contest could be good !

**Comment by Max1Truc** [comment]
Was this PR merged ?

**Comment by Max1Truc** [comment]
I can resolve the conflicts and create a new PR if needed.

**Comment by Nhqml** [comment]
> I can resolve the conflicts and create a new PR if needed.

I believe there is no need to create a new branch/PR, you can work on this one.

@lportemo is it OK with you?

**Comment by Max1Truc** [comment]
@lportemo

**Comment by juli0z** [comment]
Migrated to https://gitlab.com/prologin/concours/site/-/merge_requests/331

**Pull request closed without merging**
