### PR TITLE
forum: add an IRC webchat

### PR DESCRIPTION
**Pull request by multun**

### CODE REVIEW

**Comment by audebert** [comment]
Can you show a screenshot?

**Comment by multun** [comment]
2019-06-06-131512_1092x748_scrot

**Comment by multun** [comment]
2019-06-06-132817_819x748_scrot

**Review by seirl — CHANGES_REQUESTED** [review]
Please put the webchat under the forum.

**Comment by zopieux** [comment]
Oh wow, it has been 6 months now. I'm not sure I want this but yeah it's very obnoxious at the top. Put it below. There is a lot of room.

**Comment by lportemo** [comment]
No longer relevant, closing this.

**Pull request closed without merging**
